/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 route_66_adventure_-_sketchfab_challenge.glb 
Author: Warkarma (https://sketchfab.com/warkarma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/route-66-adventure-sketchfab-challenge-04e2aca372564da98a7ac481eac31167
Title: Route 66 adventure - Sketchfab Challenge
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/route_66_adventure_-_sketchfab_challenge.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.46, 0, -7.814]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.AirConFan__0.geometry} material={materials.AirConFan__0} position={[0.298, -0.099, 0.788]} />
        <mesh geometry={nodes.AirCon_AirCon_0.geometry} material={materials.AirCon} />
        <mesh geometry={nodes.AirCon001_AirCon_0.geometry} material={materials.AirCon} position={[-0.343, -0.17, 0.749]} rotation={[0, -Math.PI / 2, 0]} />
      </group>
      <group position={[-2.885, 0, 0.629]} rotation={[-Math.PI / 2, 0, -0.04]}>
        <mesh geometry={nodes.rock273__0.geometry} material={materials.AirConFan__0} />
        <mesh geometry={nodes.rock274__0.geometry} material={materials.AirConFan__0} />
        <mesh geometry={nodes.rock275__0.geometry} material={materials.AirConFan__0} />
        <mesh geometry={nodes.rock276__0.geometry} material={materials.AirConFan__0} />
        <mesh geometry={nodes.rock277__0.geometry} material={materials.AirConFan__0} />
        <mesh geometry={nodes.rock278__0.geometry} material={materials.AirConFan__0} />
        <mesh geometry={nodes.rock279__0.geometry} material={materials.AirConFan__0} />
        <mesh geometry={nodes.rock280__0.geometry} material={materials.AirConFan__0} />
        <mesh geometry={nodes.rock281__0.geometry} material={materials.AirConFan__0} />
        <mesh geometry={nodes.rock282__0.geometry} material={materials.AirConFan__0} />
        <mesh geometry={nodes.rock283__0.geometry} material={materials.AirConFan__0} />
        <mesh geometry={nodes.rock284__0.geometry} material={materials.AirConFan__0} />
        <mesh geometry={nodes.rock285__0.geometry} material={materials.AirConFan__0} />
      </group>
      <group position={[0.024, 0, -5.199]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Window002_DoorWindow_0.geometry} material={materials.DoorWindow} position={[4.478, -0.26, 1.477]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Window001_DoorWindow_0.geometry} material={materials.DoorWindow} position={[3.079, -2.544, 1.477]} />
        <mesh geometry={nodes.Window000_DoorWindow_0.geometry} material={materials.DoorWindow} position={[1.024, -2.544, 1.477]} />
        <mesh geometry={nodes.Walls_Walls_0.geometry} material={materials.Walls} />
        <mesh geometry={nodes.Support_Support_0.geometry} material={materials.Support} />
        <mesh geometry={nodes.Sidewalk_Sidewalk_0.geometry} material={materials.Sidewalk} position={[-4.254, 0.35, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.RoofTiles_RoofTiles_0.geometry} material={materials.RoofTiles} />
        <mesh geometry={nodes.Door_DoorWindow_0.geometry} material={materials.DoorWindow} position={[-1.955, -2.579, 1.031]} />
        <mesh geometry={nodes.Curb_Curb_0.geometry} material={materials.Curb} position={[-0.273, -5.833, 0.057]} />
        <mesh geometry={nodes.BalconyPump_BalconyPump_0.geometry} material={materials.BalconyPump} position={[-0.375, -5.845, 0]} />
        <mesh geometry={nodes.Balcony_Balcony_0.geometry} material={materials.Balcony} position={[4.494, -0.525, -0.002]} />
        <mesh geometry={nodes.Backdoor_DoorWindow_0.geometry} material={materials.DoorWindow} position={[-2.733, 2.069, 0]} rotation={[0, 0, -Math.PI]} />
      </group>
      <group position={[-0.294, -0.065, 5.187]} rotation={[-1.595, 0.017, 1.554]} scale={0.902}>
        <mesh geometry={nodes.Boardpole001_Boardpole_0.geometry} material={materials['Board.pole']} />
        <mesh geometry={nodes.Boarlogo_Boarlogo_0.geometry} material={materials['Boar.logo']} />
        <mesh geometry={nodes.Boardetails001_BoardDetails_0.geometry} material={materials['Board.Details']} />
        <mesh geometry={nodes.BoarArrow_BoarArrow_0.geometry} material={materials['Boar.Arrow']} />
      </group>
      <mesh geometry={nodes.Skip_Skip_0.geometry} material={materials.Skip} position={[-7.066, 0, -3.413]} rotation={[-Math.PI / 2, 0, 0]} />
      <group position={[5.488, 0, -6.431]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock325_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock326_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock327_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock328_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock329_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock330_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock331_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock332_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock333_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock334_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock335_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock336_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock337_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[-8.728, 0, 2.695]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock299_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock300_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock301_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock302_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock303_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock304_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock305_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock306_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock307_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock308_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock309_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock310_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock311_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock312_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock313_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock314_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock315_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock316_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock317_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock318_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock319_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock320_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock321_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock322_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock323_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock324_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[7.543, 0, 2.971]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock338_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock339_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock340_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock341_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock342_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock343_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock344_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock345_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock346_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock347_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock348_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock349_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock350_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock351_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock352_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock353_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock354_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock355_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock356_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock357_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock358_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock359_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock360_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock361_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock362_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock363_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[2.105, 0, 5.654]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock364_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock365_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock366_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock367_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock368_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock369_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock370_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock371_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock372_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock373_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock374_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock375_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock376_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[0.847, 0, 4.476]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock377_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock378_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock379_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock380_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock381_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock382_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock383_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock384_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock385_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock386_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock387_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock388_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock389_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock390_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock391_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock392_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock393_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock394_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock395_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock396_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock397_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock398_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock399_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock400_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock401_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock402_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[-3.666, 0, 4.373]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock403_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock404_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock405_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock406_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock407_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock408_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock409_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock410_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock411_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock412_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock413_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock414_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock415_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[-4.893, 0, 4.798]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock416_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock417_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock418_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock419_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock420_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock421_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock422_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock423_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock424_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock425_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock426_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock427_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock428_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock429_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock430_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock431_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock432_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock433_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock434_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock435_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock436_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock437_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock438_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock439_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock440_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock441_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[-8.787, 0, 1.454]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock442_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock443_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock444_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock445_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock446_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock447_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock448_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock449_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock450_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock451_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock452_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock453_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock454_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[-5.35, 0, -2.011]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock455_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock456_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock457_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock458_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock459_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock460_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock461_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock462_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock463_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock464_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock465_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock466_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock467_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock468_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock469_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock470_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock471_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock472_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock473_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock474_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock475_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock476_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock477_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock478_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock479_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock480_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[-8.064, 0, -2.699]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock481_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock482_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock483_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock484_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock485_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock486_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock487_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock488_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock489_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock490_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock491_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock492_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock493_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock494_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock495_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock496_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock497_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock498_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock499_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock500_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock501_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock502_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock503_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock504_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock505_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock506_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[-8.717, 0, -0.671]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock507_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock508_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock509_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock510_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock511_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock512_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock513_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock514_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock515_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock516_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock517_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock518_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock519_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock520_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock521_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock522_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock523_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock524_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock525_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock526_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock527_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock528_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock529_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock530_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock531_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock532_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[-5.865, 0, -5.671]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock533_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock534_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock535_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock536_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock537_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock538_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock539_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock540_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock541_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock542_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock543_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock544_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock545_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock546_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock547_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock548_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock549_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock550_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock551_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock552_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock553_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock554_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock555_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock556_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock557_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock558_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[7.097, 0, -4.781]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock559_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock560_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock561_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock562_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock563_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock564_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock565_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock566_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock567_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock568_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock569_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock570_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock571_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[5.722, 0, -2.908]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock572_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock573_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock574_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock575_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock576_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock577_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock578_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock579_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock580_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock581_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock582_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock583_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock584_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[-0.957, 0, -1.937]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock585_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock586_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock587_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock588_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock589_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock590_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock591_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock592_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock593_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock594_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock595_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock596_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock597_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[2.75, 0, 0.116]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock598_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock599_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock600_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock601_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock602_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock603_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock604_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock605_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock606_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock607_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock608_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock609_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock610_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[8.928, 0, -0.31]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock611_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock612_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock613_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock614_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock615_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock616_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock617_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock618_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock619_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock620_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock621_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock622_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock623_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock624_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock625_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock626_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock627_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock628_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock629_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock630_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock631_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock632_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock633_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock634_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock635_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock636_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[-7.327, 0, -0.113]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock637_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock638_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock639_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock640_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock641_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock642_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock643_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock644_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock645_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock646_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock647_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock648_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock649_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock650_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock651_Rocks_0.geometry} material={materials.Rocks} position={[0.013, -0.013, -0.017]} />
        <mesh geometry={nodes.rock652_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock653_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock654_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock655_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock656_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock657_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock658_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock659_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock660_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock661_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock662_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[-2.122, 0, -7.894]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rock663_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock664_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock666_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock667_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock668_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock669_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock671_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock672_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock674_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock676_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock677_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock678_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock679_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock681_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock682_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock683_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock684_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock685_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock686_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock687_Rocks_0.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.rock688_Rocks_0.geometry} material={materials.Rocks} />
      </group>
      <group position={[0.836, 0, 2.169]} rotation={[-Math.PI / 2, 0, -3.045]}>
        <group position={[1.287, 0.018, 0.682]} rotation={[0, 0.282, 1.599]} scale={0.899}>
          <mesh geometry={nodes.Toilet002_Props3_0.geometry} material={materials.Props3} position={[-0.169, 0.247, 0.522]} rotation={[-1.101, 0.184, 0.341]} />
          <mesh geometry={nodes.Toilet001_Props3_0.geometry} material={materials.Props3} position={[0.159, 0.234, 0.516]} rotation={[0.241, -0.471, 0.139]} />
          <mesh geometry={nodes.Shovel_Props3_0.geometry} material={materials.Props3} position={[-0.252, 0.028, 0.262]} rotation={[0.04, -0.081, -0.547]} />
          <mesh geometry={nodes.Radio_Props3_0.geometry} material={materials.Props3} position={[-0.004, 0.078, 0.581]} rotation={[0.117, -0.009, -0.073]} />
          <mesh geometry={nodes.Pan_Props3_0.geometry} material={materials.Props3} position={[-0.029, 0.321, 0.609]} rotation={[-1.461, 0.302, -1.621]} />
          <mesh geometry={nodes.MedPack_Backpack_0.geometry} material={materials.Backpack} position={[-0.004, -0.101, 0.139]} />
          <mesh geometry={nodes.ladle_Props3_0.geometry} material={materials.Props3} position={[0.12, 0.164, 0.43]} rotation={[1.907, -0.333, 2.411]} />
          <mesh geometry={nodes.Knife_Props3_0.geometry} material={materials.Props3} position={[0.083, 0.017, 0.492]} rotation={[2.215, 1.558, -2.329]} scale={0.873} />
          <mesh geometry={nodes.Hatchet_Props3_0.geometry} material={materials.Props3} position={[0.223, 0.034, 0.314]} rotation={[0.091, 0.034, -2.689]} scale={1.194} />
          <mesh geometry={nodes.Flashlight_Props3_0.geometry} material={materials.Props3} position={[-0.127, -0.019, 0.345]} rotation={[-2.535, 0.848, 2.619]} scale={1.335} />
          <mesh geometry={nodes.Cup_Props3_0.geometry} material={materials.Props3} position={[-0.32, 0.228, 0.294]} rotation={[0.693, 0.323, -0.818]} />
          <mesh geometry={nodes.Compas_Props3_0.geometry} material={materials.Props3} position={[0.102, -0.09, 0.283]} rotation={[-0.644, -0.461, 1.064]} />
          <mesh geometry={nodes.Coke002_Props3_0.geometry} material={materials.Props3} position={[0.088, 0.099, 0.396]} rotation={[-0.078, 0.151, -1.423]} />
          <mesh geometry={nodes.Coke001_Props3_0.geometry} material={materials.Props3} position={[0.125, 0.112, 0.415]} rotation={[-0.32, 0.362, 0.011]} />
          <mesh geometry={nodes.Coffee_Props3_0.geometry} material={materials.Props3} position={[0.286, 0.267, 0.275]} rotation={[-0.116, 0.047, 1.419]} />
          <mesh geometry={nodes.Chess_Props3_0.geometry} material={materials.Props3} position={[-0.19, 0.064, 0.542]} rotation={[0.132, 0.017, 1.664]} />
        </group>
        <mesh geometry={nodes.Book_Proprs2_0.geometry} material={materials.Proprs2} position={[0.907, 0.433, 0.531]} rotation={[-1.598, 0.045, -2.982]} />
        <mesh geometry={nodes.Pan003_Props3_0.geometry} material={materials.Props3} position={[-0.909, -0.154, 1.054]} rotation={[1.117, 0, 0]} />
        <mesh geometry={nodes.Motorcyle001_Motorcyle_0.geometry} material={materials.Motorcyle} />
        <mesh geometry={nodes.Motorcyle002_Motorcyle_0.geometry} material={materials.Motorcyle} />
        <mesh geometry={nodes.Motorcyle002_Motorcyle_0_1.geometry} material={materials.Motorcyle} />
        <mesh geometry={nodes.Motorcyle002_Motorcyle_0_2.geometry} material={materials.Motorcyle} />
        <mesh geometry={nodes.kettle001_Props3_0.geometry} material={materials.Props3} position={[-0.903, 0.235, 0.847]} rotation={[0, 0, 3.038]} />
        <mesh geometry={nodes.JerryCan003_Props3_0.geometry} material={materials.Props3} position={[0.794, -0.332, 0.351]} />
        <mesh geometry={nodes.Chicken001_Chicken_0.geometry} material={materials.Chicken} position={[-1.12, -0.002, 0.829]} rotation={[0, 0, -Math.PI / 2]} scale={0.346} />
        <mesh geometry={nodes.Bucket001_Props3_0.geometry} material={materials.Props3} position={[1.089, 0.326, 0.598]} rotation={[0.024, -0.556, 1.243]} />
        <mesh geometry={nodes.Bag_Props3_0.geometry} material={materials.Props3} position={[0.777, 0.325, 0.422]} rotation={[0, 0.268, 0]} />
      </group>
      <group position={[0.67, 0, 2.551]} rotation={[-Math.PI / 2, 0, 0.202]}>
        <mesh geometry={nodes.Bunny_Bunny_0.geometry} material={materials.Bunny} />
        <mesh geometry={nodes.Map_Props3_0.geometry} material={materials.Props3} position={[-0.119, -0.489, 1.015]} rotation={[-0.538, 0, Math.PI]} />
        <mesh geometry={nodes.Bunny001__0.geometry} material={materials.AirConFan__0} position={[0, 0.111, 1.185]} />
      </group>
      <mesh geometry={nodes.Signs_Signs_0.geometry} material={materials.Signs} position={[4.37, 1.339, -2.619]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Signs001_Signs_0.geometry} material={materials.Signs} position={[3.277, 2.469, -2.621]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Signs002_Signs_0.geometry} material={materials.Signs} position={[-0.275, 1.379, -2.618]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Signs003_Signs_0.geometry} material={materials.Signs} position={[2.504, 0.046, -2.452]} rotation={[-1.799, 0.063, -0.014]} />
      <mesh geometry={nodes.Signs004_Signs_0.geometry} material={materials.Signs} position={[3.152, 0.139, -2.653]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Signs005_Signs_0.geometry} material={materials.Signs} position={[0.16, 0.512, -2.653]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Signs006_Signs_0.geometry} material={materials.Signs} position={[-1.662, 2.353, -2.602]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Signs007_Signs_0.geometry} material={materials.Signs} position={[1.691, 1.827, 0.655]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Signs008_Signs_0.geometry} material={materials.Signs} position={[-0.42, 2.876, 1.396]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.TrafficCone_Props1_0.geometry} material={materials.Props1} position={[7.265, 0, 4.086]} rotation={[-Math.PI / 2, 0, 1.062]} />
      <mesh geometry={nodes.TrafficCone001_Props1_0.geometry} material={materials.Props1} position={[6.638, 0, 3.126]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.TrafficCone002_Props1_0.geometry} material={materials.Props1} position={[6.639, 0, 1.966]} rotation={[-Math.PI / 2, 0, 0.686]} />
      <mesh geometry={nodes.TrafficCone003_Props1_0.geometry} material={materials.Props1} position={[6.652, 0, 0.671]} rotation={[-Math.PI / 2, 0, -0.738]} />
      <mesh geometry={nodes.TrafficCone004_Props1_0.geometry} material={materials.Props1} position={[-5.46, 0, 3.941]} rotation={[-Math.PI / 2, 0, 2.493]} />
      <mesh geometry={nodes.TrafficCone005_Props1_0.geometry} material={materials.Props1} position={[-6.52, 0, 4.662]} rotation={[-Math.PI / 2, 0, 0.366]} />
      <mesh geometry={nodes.TrafficCone007_Props1_0.geometry} material={materials.Props1} position={[-9.385, 0, 1.881]} rotation={[-Math.PI / 2, 0, 0.121]} />
      <mesh geometry={nodes.TrafficCone008_Props1_0.geometry} material={materials.Props1} position={[-8.305, 0, 0.801]} rotation={[-Math.PI / 2, 0, -1.83]} />
      <mesh geometry={nodes.Pallet_Props1_0.geometry} material={materials.Props1} position={[2.923, 0.445, -7.739]} rotation={[-2.354, 0.062, 3.08]} />
      <mesh geometry={nodes.Pallet001_Props1_0.geometry} material={materials.Props1} position={[1.896, 0.592, -7.457]} rotation={[-2.833, -0.044, -3.129]} />
      <mesh geometry={nodes.Pallet002_Props1_0.geometry} material={materials.Props1} position={[-7.085, 0.303, -2.648]} rotation={[-1.858, -0.007, -3.116]} />
      <mesh geometry={nodes.Propeller_Proprs2_0.geometry} material={materials.Proprs2} position={[-0.267, 2.257, -2.633]} rotation={[Math.PI / 2, -0.201, Math.PI]} />
      <mesh geometry={nodes.ElectricBox_Proprs2_0.geometry} material={materials.Proprs2} position={[-4.036, 1.513, -3.673]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.IceMachine_IceMachine_0.geometry} material={materials.IceMachine} position={[4.916, -0.001, -6.348]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Fridge_Fridge_0.geometry} material={materials.Fridge} position={[-7.023, 1.259, -4.668]} rotation={[-1.834, 0.759, 0.117]} />
      <mesh geometry={nodes.Gas001_Proprs2_0.geometry} material={materials.Proprs2} position={[1.157, -0.001, -2.44]} rotation={[-Math.PI / 2, 0, -2.356]} />
      <mesh geometry={nodes.Gas_Proprs2_0.geometry} material={materials.Proprs2} position={[1.471, -0.001, -2.44]} rotation={[-Math.PI / 2, 0, -0.407]} />
      <mesh geometry={nodes.Gas002_Proprs2_0.geometry} material={materials.Proprs2} position={[-4.235, -0.001, -4.709]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Gas003_Proprs2_0.geometry} material={materials.Proprs2} position={[-4.849, -0.001, -4.646]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Gas004_Proprs2_0.geometry} material={materials.Proprs2} position={[-5.144, -0.001, -4.954]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Gas005_Proprs2_0.geometry} material={materials.Proprs2} position={[-6.796, -4.193, 0.673]} rotation={[-1.256, -0.73, 0.03]} />
      <mesh geometry={nodes.Tumbleweed_Tumbleweed_0.geometry} material={materials.Tumbleweed} position={[-8.218, -0.001, -0.747]} rotation={[-Math.PI / 2, 0, 0]} scale={0.892} />
      <mesh geometry={nodes.Tumbleweed001_Tumbleweed_0.geometry} material={materials.Tumbleweed} position={[-8.376, -0.001, -2.431]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Tumbleweed002_Tumbleweed_0.geometry} material={materials.Tumbleweed} position={[-7.94, -0.001, -1.59]} rotation={[-Math.PI / 2, 0, 0]} scale={0.436} />
      <mesh geometry={nodes.Tumbleweed005_Tumbleweed_0.geometry} material={materials.Tumbleweed} position={[0.968, -0.001, 5.78]} rotation={[-Math.PI / 2, 0, 0]} scale={0.631} />
      <mesh geometry={nodes.CardbordBox003_Props1_0.geometry} material={materials.Props1} position={[4.781, 0.283, -3.357]} rotation={[-1.628, -0.005, -0.175]} />
      <mesh geometry={nodes.CardbordBox002_Props1_0.geometry} material={materials.Props1} position={[4.776, 0.148, -2.954]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.CardbordBox001_Props1_0.geometry} material={materials.Props1} position={[4.761, 0.169, -3.992]} rotation={[-Math.PI / 2, 0, -1.484]} />
      <mesh geometry={nodes.CardbordBox_Props1_0.geometry} material={materials.Props1} position={[4.809, 0.098, -3.354]} rotation={[-Math.PI / 2, 0, 0.085]} />
      <mesh geometry={nodes.CardbordBox004_Props1_0.geometry} material={materials.Props1} position={[1.297, 0.261, -8.132]} rotation={[-Math.PI / 2, 0, -0.175]} />
      <mesh geometry={nodes.CardbordBox005_Props1_0.geometry} material={materials.Props1} position={[0.949, 0.148, -7.541]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.CardbordBox006_Props1_0.geometry} material={materials.Props1} position={[0.492, 0.156, -8.156]} rotation={[-Math.PI / 2, 0, -1.484]} />
      <mesh geometry={nodes.CardbordBox007_Props1_0.geometry} material={materials.Props1} position={[1.369, 0.082, -8.069]} rotation={[-Math.PI / 2, 0, 0.085]} />
      <mesh geometry={nodes.CardbordBox008_Props1_0.geometry} material={materials.Props1} position={[-7.513, 0.613, -2.123]} rotation={[-1.868, 0.003, -0.122]} />
      <mesh geometry={nodes.CardbordBox009_Props1_0.geometry} material={materials.Props1} position={[-6.776, 0.344, -3.209]} rotation={[2.851, -0.077, -0.008]} />
      <mesh geometry={nodes.CardbordBox010_Props1_0.geometry} material={materials.Props1} position={[-6.892, 0.795, -2.563]} rotation={[-2.56, -0.113, -1.445]} />
      <mesh geometry={nodes.CardbordBox011_Props1_0.geometry} material={materials.Props1} position={[-7.335, 0.205, -4.343]} rotation={[2.202, -0.077, -0.105]} />
      <mesh geometry={nodes.Tumbleweed004_Tumbleweed_0.geometry} material={materials.Tumbleweed} position={[-8.951, -0.001, -3.001]} rotation={[-Math.PI / 2, 0, 0]} scale={0.616} />
      <mesh geometry={nodes.Tumbleweed006_Tumbleweed_0.geometry} material={materials.Tumbleweed} position={[-8.882, -0.001, -1.996]} rotation={[-Math.PI / 2, 0, 0]} scale={0.393} />
      <mesh geometry={nodes.Crate_Props1_0.geometry} material={materials.Props1} position={[-6.859, 0.499, -2.584]} rotation={[-1.858, -0.008, 0.171]} />
      <mesh geometry={nodes.Crate001_Props1_0.geometry} material={materials.Props1} position={[-7.31, 1.25, -4.032]} rotation={[-2.643, 0.516, -2.425]} />
      <mesh geometry={nodes.Crate002_Props1_0.geometry} material={materials.Props1} position={[-1.571, -0.014, -7.843]} rotation={[-Math.PI / 2, 0, -1.513]} />
      <mesh geometry={nodes.Crate003_Props1_0.geometry} material={materials.Props1} position={[-1.571, 0.253, -7.843]} rotation={[-Math.PI / 2, 0, 1.58]} />
      <mesh geometry={nodes.Crate004_Props1_0.geometry} material={materials.Props1} position={[-1.571, 0.522, -7.843]} rotation={[-Math.PI / 2, 0, -1.599]} />
      <mesh geometry={nodes.JerryCan001_Props3_0.geometry} material={materials.Props3} position={[1.812, 0.01, -2.338]} rotation={[-Math.PI / 2, 0, -1.554]} />
      <mesh geometry={nodes.JerryCan002_Props3_0.geometry} material={materials.Props3} position={[2.091, 0.01, -2.345]} rotation={[-Math.PI / 2, 0, 1.597]} />
      <mesh geometry={nodes.Gas006_Proprs2_0.geometry} material={materials.Proprs2} position={[0.812, -0.001, -2.44]} rotation={[-Math.PI / 2, 0, 0.576]} />
      <mesh geometry={nodes.Signs009_Signs_0.geometry} material={materials.Signs} position={[-0.886, 0.512, -2.653]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Signs010_Signs_0.geometry} material={materials.Signs} position={[-3.282, 1.688, -2.653]} rotation={[-Math.PI / 2, 0, 0]} scale={1.826} />
      <mesh geometry={nodes.CokeFridge_CokeFridge_0.geometry} material={materials.CokeFridge} position={[-3.255, 0.011, -2.256]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.CactusDesert_CactusDesert_0.geometry} material={materials.CactusDesert} position={[8.675, -0.001, 3.368]} rotation={[-1.621, -0.028, 0.528]} scale={1.057} />
      <mesh geometry={nodes.CactusDesert001_CactusDesert_0.geometry} material={materials.CactusDesert} position={[-4.645, -0.001, 5.645]} rotation={[-1.515, 0.016, -2.398]} scale={0.529} />
      <mesh geometry={nodes.CactusNopal_CactusNopal_0.geometry} material={materials.CactusNopal} position={[-8.937, -0.001, 0.734]} rotation={[-1.621, -0.047, -3.032]} />
      <mesh geometry={nodes.CactusNopal002_CactusNopal_0.geometry} material={materials.CactusNopal} position={[-9.244, -0.001, 0.812]} rotation={[-1.533, 0.008, -1.505]} />
      <mesh geometry={nodes.CactusNopal001_CactusNopal_0.geometry} material={materials.CactusNopal} position={[-8.871, -0.001, 0.499]} rotation={[-1.533, -0.053, -0.038]} scale={1.055} />
      <mesh geometry={nodes.CactusDesert004_CactusDesert_0.geometry} material={materials.CactusDesert} position={[-5.17, -0.001, 5.407]} rotation={[-1.496, -0.025, -2.805]} scale={0.664} />
      <mesh geometry={nodes.CactusDesert003_CactusDesert_0.geometry} material={materials.CactusDesert} position={[-9.496, -0.001, 0.364]} rotation={[-1.565, 0.024, 0.298]} scale={0.804} />
      <mesh geometry={nodes.CactusDesert002_CactusDesert_0.geometry} material={materials.CactusDesert} position={[-4.604, -0.001, 5.193]} rotation={[-1.596, -0.007, -2.398]} />
      <mesh geometry={nodes.CactusDesert005_CactusDesert_0.geometry} material={materials.CactusDesert} position={[8.862, -0.001, 4.005]} rotation={[-1.622, 0.087, -0.771]} scale={0.529} />
      <mesh geometry={nodes.CactusDesert006_CactusDesert_0.geometry} material={materials.CactusDesert} position={[-9.402, -0.001, -0.223]} rotation={[-1.625, 0.003, -2.754]} scale={0.894} />
      <mesh geometry={nodes.CactusDesert007_CactusDesert_0.geometry} material={materials.CactusDesert} position={[-9.214, -0.001, 0.415]} rotation={[-1.512, 0.025, -0.524]} scale={0.529} />
      <mesh geometry={nodes.CactusNopal003_CactusNopal_0.geometry} material={materials.CactusNopal} position={[8.575, -0.001, 4.594]} rotation={[-1.508, 0.019, -2.479]} scale={0.953} />
      <mesh geometry={nodes.CactusNopal004_CactusNopal_0.geometry} material={materials.CactusNopal} position={[2.675, -0.001, 5.99]} rotation={[-1.566, -0.067, -0.711]} scale={0.952} />
      <mesh geometry={nodes.CactusNopal006_CactusNopal_0.geometry} material={materials.CactusNopal} position={[2.948, -0.001, 5.828]} rotation={[-1.587, -0.014, -1.862]} />
      <mesh geometry={nodes.CactusNopal005_CactusNopal_0.geometry} material={materials.CactusNopal} position={[2.688, -0.001, 5.744]} rotation={[-1.496, -0.009, -2.842]} />
      <mesh geometry={nodes.CactusNopal007_CactusNopal_0.geometry} material={materials.CactusNopal} position={[8.272, -0.001, 4.754]} rotation={[-1.619, -0.007, -0.594]} />
      <mesh geometry={nodes.CactusNopal008_CactusNopal_0.geometry} material={materials.CactusNopal} position={[-4.25, -0.001, 5.406]} rotation={[-1.572, -0.092, -2.079]} />
      <mesh geometry={nodes.CactusNopal009_CactusNopal_0.geometry} material={materials.CactusNopal} position={[-8.794, -0.001, 0.001]} rotation={[-1.628, -0.018, 0.474]} />
      <mesh geometry={nodes.CactusNopal010_CactusNopal_0.geometry} material={materials.CactusNopal} position={[-8.368, -0.001, -0.19]} rotation={[-1.535, -0.034, -3.106]} scale={1.055} />
      <mesh geometry={nodes.CactusNopal011_CactusNopal_0.geometry} material={materials.CactusNopal} position={[2.869, -0.001, 5.596]} rotation={[-1.632, 0.027, -2.773]} scale={0.952} />
      <mesh geometry={nodes.CactusDesert008_CactusDesert_0.geometry} material={materials.CactusDesert} position={[4.474, -0.001, -7.783]} rotation={[-1.621, -0.028, 0.528]} scale={1.151} />
      <mesh geometry={nodes.CactusDesert009_CactusDesert_0.geometry} material={materials.CactusDesert} position={[-8.761, -0.001, -1.405]} rotation={[-1.621, -0.028, 0.528]} scale={1.248} />
      <mesh geometry={nodes.BushDry_Foliage_0.geometry} material={materials.Foliage} position={[-2.83, -0.001, 0.874]} rotation={[-Math.PI / 2, 0, 0]} scale={1.168} />
      <mesh geometry={nodes.BushDry001_Foliage_0.geometry} material={materials.Foliage} position={[2.444, -0.001, 0.437]} rotation={[-Math.PI / 2, 0, 0]} scale={0.538} />
      <mesh geometry={nodes.BushDry002_Foliage_0.geometry} material={materials.Foliage} position={[-2.8, -0.001, 0.945]} rotation={[-Math.PI / 2, 0, 0]} scale={0.332} />
      <mesh geometry={nodes.BushDry003_Foliage_0.geometry} material={materials.Foliage} position={[0.436, -0.001, 5.203]} rotation={[-Math.PI / 2, 0, 0]} scale={0.223} />
      <mesh geometry={nodes.BushDry004_Foliage_0.geometry} material={materials.Foliage} position={[0.52, -0.001, 5.044]} rotation={[-Math.PI / 2, 0, 0]} scale={0.835} />
      <mesh geometry={nodes.BushDry005_Foliage_0.geometry} material={materials.Foliage} position={[0.324, -0.001, 5.292]} rotation={[-Math.PI / 2, 0, 0]} scale={1.168} />
      <mesh geometry={nodes.BushDry006_Foliage_0.geometry} material={materials.Foliage} position={[-0.843, -0.001, 5.57]} rotation={[-Math.PI / 2, 0, 0]} scale={0.835} />
      <mesh geometry={nodes.BushDry007_Foliage_0.geometry} material={materials.Foliage} position={[-0.765, -0.001, 5.699]} rotation={[-Math.PI / 2, 0, 0]} scale={0.223} />
      <mesh geometry={nodes.BushDry008_Foliage_0.geometry} material={materials.Foliage} position={[2.808, -0.001, 5.777]} rotation={[-Math.PI / 2, 0, 0]} scale={1.168} />
      <mesh geometry={nodes.BushDry009_Foliage_0.geometry} material={materials.Foliage} position={[8.134, -0.001, 4.588]} rotation={[-Math.PI / 2, 0, 0]} scale={0.835} />
      <mesh geometry={nodes.BushDry010_Foliage_0.geometry} material={materials.Foliage} position={[-5.445, -0.001, 5.384]} rotation={[-Math.PI / 2, 0, 0]} scale={0.223} />
      <mesh geometry={nodes.BushDry011_Foliage_0.geometry} material={materials.Foliage} position={[-5.476, -0.001, 5.47]} rotation={[-Math.PI / 2, 0, 1.056]} scale={3.053} />
      <mesh geometry={nodes.BushDry012_Foliage_0.geometry} material={materials.Foliage} position={[-7.712, -0.001, -0.033]} rotation={[-Math.PI / 2, 0, 0]} scale={1.284} />
      <mesh geometry={nodes.BushDry013_Foliage_0.geometry} material={materials.Foliage} position={[-8.196, -0.001, -0.033]} rotation={[-Math.PI / 2, 0, -1.211]} scale={0.223} />
      <mesh geometry={nodes.BushDry014_Foliage_0.geometry} material={materials.Foliage} position={[-7.932, -0.001, -0.033]} rotation={[-Math.PI / 2, 0, 0]} scale={1.179} />
      <mesh geometry={nodes.BushDry015_Foliage_0.geometry} material={materials.Foliage} position={[-8.651, -0.001, -0.253]} rotation={[-Math.PI / 2, 0, 0]} scale={0.241} />
      <mesh geometry={nodes.BushDry016_Foliage_0.geometry} material={materials.Foliage} position={[-8.823, -0.001, 0.233]} rotation={[-Math.PI / 2, 0, 0]} scale={0.223} />
      <mesh geometry={nodes.BushDry017_Foliage_0.geometry} material={materials.Foliage} position={[-8.548, -0.001, 0.195]} rotation={[-Math.PI / 2, 0, 0]} scale={1.168} />
      <mesh geometry={nodes.BushDry018_Foliage_0.geometry} material={materials.Foliage} position={[-8.993, -0.001, -0.307]} rotation={[-Math.PI / 2, 0, 0]} scale={1.168} />
      <mesh geometry={nodes.BushDry019_Foliage_0.geometry} material={materials.Foliage} position={[-7.629, -0.001, -0.519]} rotation={[-Math.PI / 2, 0, 0]} scale={1.168} />
      <mesh geometry={nodes.BushDry020_Foliage_0.geometry} material={materials.Foliage} position={[-8.805, -0.001, -0.507]} rotation={[-Math.PI / 2, 0, 0]} scale={0.835} />
      <mesh geometry={nodes.BushDry021_Foliage_0.geometry} material={materials.Foliage} position={[8.617, -0.001, 3.678]} rotation={[-Math.PI / 2, 0, 0]} scale={1.168} />
      <mesh geometry={nodes.BushDry022_Foliage_0.geometry} material={materials.Foliage} position={[5.19, -0.001, -3.395]} rotation={[-Math.PI / 2, 0, 0]} scale={1.109} />
      <mesh geometry={nodes.BushDry023_Foliage_0.geometry} material={materials.Foliage} position={[4.447, -0.001, -8.033]} rotation={[-Math.PI / 2, 0, 0]} scale={0.256} />
      <mesh geometry={nodes.BushDry024_Foliage_0.geometry} material={materials.Foliage} position={[6.622, -0.001, -4.482]} rotation={[-Math.PI / 2, 0, 0]} scale={0.339} />
      <mesh geometry={nodes.BushDry025_Foliage_0.geometry} material={materials.Foliage} position={[6.116, -0.001, -3.358]} rotation={[-Math.PI / 2, 0, 0]} scale={1.927} />
      <mesh geometry={nodes.BushDry026_Foliage_0.geometry} material={materials.Foliage} position={[5.357, -0.001, -7.063]} rotation={[-Math.PI / 2, 0, 0]} scale={0.298} />
      <mesh geometry={nodes.BushDry027_Foliage_0.geometry} material={materials.Foliage} position={[5.09, -0.001, -7.191]} rotation={[-Math.PI / 2, 0, 0]} scale={1.759} />
      <mesh geometry={nodes.BushDry028_Foliage_0.geometry} material={materials.Foliage} position={[5.425, -0.001, -6.896]} rotation={[-Math.PI / 2, 0, 0]} scale={1.168} />
      <mesh geometry={nodes.BushDry029_Foliage_0.geometry} material={materials.Foliage} position={[5.144, -0.001, -5.458]} rotation={[-Math.PI / 2, 0, 0]} scale={0.284} />
      <mesh geometry={nodes.BushDry030_Foliage_0.geometry} material={materials.Foliage} position={[5.277, -0.001, -5.499]} rotation={[-Math.PI / 2, 0, 0]} scale={1.168} />
      <mesh geometry={nodes.BushDry031_Foliage_0.geometry} material={materials.Foliage} position={[5.35, -0.001, -7.259]} rotation={[-Math.PI / 2, 0, 0]} scale={1.168} />
      <mesh geometry={nodes.BushDry032_Foliage_0.geometry} material={materials.Foliage} position={[7.541, -0.001, -4.39]} rotation={[-Math.PI / 2, 0, 0]} scale={1.168} />
      <mesh geometry={nodes.BushDry033_Foliage_0.geometry} material={materials.Foliage} position={[-4.603, -0.001, -6.564]} rotation={[-Math.PI / 2, 0, 0]} scale={0.317} />
      <mesh geometry={nodes.BushDry034_Foliage_0.geometry} material={materials.Foliage} position={[-1.184, -0.001, -8.45]} rotation={[-Math.PI / 2, 0, 0]} scale={0.465} />
      <mesh geometry={nodes.BushDry035_Foliage_0.geometry} material={materials.Foliage} position={[-4.891, -0.001, -5.74]} rotation={[-Math.PI / 2, 0, 0]} scale={0.377} />
      <mesh geometry={nodes.BushDry036_Foliage_0.geometry} material={materials.Foliage} position={[-4.583, -0.001, -6.726]} rotation={[-Math.PI / 2, 0, 0]} scale={1.168} />
      <mesh geometry={nodes.BushDry037_Foliage_0.geometry} material={materials.Foliage} position={[-7.921, -0.001, -2.69]} rotation={[-Math.PI / 2, 0, 0]} scale={1.168} />
      <mesh geometry={nodes.BushDry038_Foliage_0.geometry} material={materials.Foliage} position={[-1.36, -0.001, -8.38]} rotation={[-Math.PI / 2, 0, 0]} scale={1.168} />
      <mesh geometry={nodes.BushDry039_Foliage_0.geometry} material={materials.Foliage} position={[1.084, -0.001, -7.784]} rotation={[-Math.PI / 2, 0, 0]} scale={1.168} />
      <mesh geometry={nodes.Beer003_Proprs2_0.geometry} material={materials.Proprs2} position={[6.379, 0.618, -4.529]} rotation={[-Math.PI / 2, 0, -1.505]} />
      <mesh geometry={nodes.Beer004_Proprs2_0.geometry} material={materials.Proprs2} position={[6.504, 0.614, -5.288]} rotation={[-Math.PI / 2, 0, -0.04]} />
      <mesh geometry={nodes.Beer005_Proprs2_0.geometry} material={materials.Proprs2} position={[6.159, 0.617, -4.778]} rotation={[-Math.PI / 2, 0, 1.905]} />
      <mesh geometry={nodes.BeerEmpty_Proprs2_0.geometry} material={materials.Proprs2} position={[5.08, 0.03, -3.13]} rotation={[-0.003, -0.225, 1.031]} />
      <mesh geometry={nodes.BeerEmpty001_Proprs2_0.geometry} material={materials.Proprs2} position={[5.379, 0.027, -5.582]} rotation={[-3.139, 0.376, -2.111]} />
      <mesh geometry={nodes.BeerEmpty002_Proprs2_0.geometry} material={materials.Proprs2} position={[6.149, 0.621, -4.516]} rotation={[-Math.PI / 2, 0, -0.597]} />
      <mesh geometry={nodes.BeerEmpty003_Proprs2_0.geometry} material={materials.Proprs2} position={[6.513, 0.621, -4.735]} rotation={[-Math.PI / 2, 0, 0.744]} />
      <mesh geometry={nodes.BeerEmpty004_Proprs2_0.geometry} material={materials.Proprs2} position={[6.468, 0.62, -4.82]} rotation={[-Math.PI / 2, 0, 1.156]} />
      <mesh geometry={nodes.BeerEmpty005_Proprs2_0.geometry} material={materials.Proprs2} position={[6.374, 0.622, -4.692]} rotation={[-Math.PI / 2, 0, -1.505]} />
      <mesh geometry={nodes.BeerEmpty006_Proprs2_0.geometry} material={materials.Proprs2} position={[6.903, 0.621, -4.144]} rotation={[-Math.PI / 2, 0, -0.04]} />
      <mesh geometry={nodes.Grass004_Foliage_0.geometry} material={materials.Foliage} position={[1.629, -0.001, -2.178]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass003_Foliage_0.geometry} material={materials.Foliage} position={[-4.477, -0.001, -2.717]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass002_Foliage_0.geometry} material={materials.Foliage} position={[-5.123, -0.001, -6.004]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass001_Foliage_0.geometry} material={materials.Foliage} position={[-5.028, -0.001, -4.737]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass000_Foliage_0.geometry} material={materials.Foliage} position={[-6.299, -0.001, -4.35]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass005_Foliage_0.geometry} material={materials.Foliage} position={[2.457, -0.001, 0.7]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass006_Foliage_0.geometry} material={materials.Foliage} position={[2.522, -0.001, 0.557]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass007_Foliage_0.geometry} material={materials.Foliage} position={[2.418, -0.001, 0.856]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass008_Foliage_0.geometry} material={materials.Foliage} position={[8.095, -0.001, 3.723]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass009_Foliage_0.geometry} material={materials.Foliage} position={[8.152, -0.001, 3.948]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass010_Foliage_0.geometry} material={materials.Foliage} position={[8.074, -0.001, 3.792]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass011_Foliage_0.geometry} material={materials.Foliage} position={[8.059, -0.001, 3.961]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass012_Foliage_0.geometry} material={materials.Foliage} position={[8.27, -0.001, 4.268]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass013_Foliage_0.geometry} material={materials.Foliage} position={[8.799, -0.001, 3.61]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass014_Foliage_0.geometry} material={materials.Foliage} position={[2.341, -0.001, 5.939]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass015_Foliage_0.geometry} material={materials.Foliage} position={[0.32, -0.001, 5.548]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass016_Foliage_0.geometry} material={materials.Foliage} position={[0.297, -0.001, 5.693]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass017_Foliage_0.geometry} material={materials.Foliage} position={[-0.835, -0.001, 5.329]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass018_Foliage_0.geometry} material={materials.Foliage} position={[-0.493, -0.001, 5.791]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass019_Foliage_0.geometry} material={materials.Foliage} position={[-0.618, -0.001, 5.777]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass020_Foliage_0.geometry} material={materials.Foliage} position={[-5.412, -0.001, 5.763]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass021_Foliage_0.geometry} material={materials.Foliage} position={[-5.749, -0.001, 5.45]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass022_Foliage_0.geometry} material={materials.Foliage} position={[-6.213, -0.001, 5.455]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass023_Foliage_0.geometry} material={materials.Foliage} position={[-6.107, -0.001, 5.505]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass024_Foliage_0.geometry} material={materials.Foliage} position={[-6.201, -0.001, 5.14]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass025_Foliage_0.geometry} material={materials.Foliage} position={[-6.064, -0.001, 5.114]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass026_Foliage_0.geometry} material={materials.Foliage} position={[-5.678, -0.001, 5.321]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass027_Foliage_0.geometry} material={materials.Foliage} position={[-6.27, -0.001, 4.71]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass028_Foliage_0.geometry} material={materials.Foliage} position={[-9.434, -0.001, 0.657]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass029_Foliage_0.geometry} material={materials.Foliage} position={[-9.616, -0.001, 0.077]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass030_Foliage_0.geometry} material={materials.Foliage} position={[-9.706, -0.001, 0.338]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass031_Foliage_0.geometry} material={materials.Foliage} position={[-9.571, -0.001, 0.587]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass032_Foliage_0.geometry} material={materials.Foliage} position={[-2.857, -0.001, 0.412]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass033_Foliage_0.geometry} material={materials.Foliage} position={[-3.9, -0.001, -2.116]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass034_Foliage_0.geometry} material={materials.Foliage} position={[-4.851, -0.001, -3.85]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass035_Foliage_0.geometry} material={materials.Foliage} position={[-7.818, -0.001, -4.414]} rotation={[-1.825, -0.348, -0.072]} />
      <mesh geometry={nodes.Grass036_Foliage_0.geometry} material={materials.Foliage} position={[-7.73, -0.001, -4.462]} rotation={[-2.267, -0.226, 0.178]} />
      <mesh geometry={nodes.Grass037_Foliage_0.geometry} material={materials.Foliage} position={[-4.921, -0.001, -5.768]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass038_Foliage_0.geometry} material={materials.Foliage} position={[-4.051, 0.034, -7.29]} rotation={[-1.83, -0.229, 0.201]} />
      <mesh geometry={nodes.Grass039_Foliage_0.geometry} material={materials.Foliage} position={[0.864, -0.001, -7.935]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass040_Foliage_0.geometry} material={materials.Foliage} position={[0.841, -0.001, -8.204]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass041_Foliage_0.geometry} material={materials.Foliage} position={[0.982, -0.001, -7.963]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass042_Foliage_0.geometry} material={materials.Foliage} position={[0.831, -0.001, -7.782]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass043_Foliage_0.geometry} material={materials.Foliage} position={[0.968, -0.001, -8.095]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass044_Foliage_0.geometry} material={materials.Foliage} position={[1.958, -0.001, -8.288]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass045_Foliage_0.geometry} material={materials.Foliage} position={[2.06, -0.001, -8.203]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass046_Foliage_0.geometry} material={materials.Foliage} position={[4.155, -0.001, -7.875]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass047_Foliage_0.geometry} material={materials.Foliage} position={[5.866, -0.001, -5.968]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass048_Foliage_0.geometry} material={materials.Foliage} position={[5.148, -0.001, -2.866]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass049_Foliage_0.geometry} material={materials.Foliage} position={[8.756, -0.001, 0.602]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Grass050_Foliage_0.geometry} material={materials.Foliage} position={[6.926, -0.001, -3.391]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LightW_Lights_0.geometry} material={materials.Lights} position={[-1.877, 2.678, -2.674]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.LightW001_Lights_0.geometry} material={materials.Lights} position={[-2.882, 2.404, -7.248]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.LightW002_Lights_0.geometry} material={materials.Lights} position={[4.495, 2.39, -4.461]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.LightC001_Lights_0.geometry} material={materials.Lights} position={[-0.338, 2.633, 0.102]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LightW004_Lights_0.geometry} material={materials.Lights} position={[-0.368, 3.482, 1.378]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.RoofVent_Props1_0.geometry} material={materials.Props1} position={[-0.343, 3.649, -6.926]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.RoofDetailL_Props1_0.geometry} material={materials.Props1} position={[-0.115, 3.624, -3.026]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.RoofDetailL002_Props1_0.geometry} material={materials.Props1} position={[-0.115, 3.624, -3.405]} rotation={[-Math.PI / 2, 0, 1.309]} />
      <mesh geometry={nodes.Flags001_Proprs2_0.geometry} material={materials.Proprs2} position={[2.329, 2.48, 1.33]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LightC002_Lights_0.geometry} material={materials.Lights} position={[-0.338, 2.633, -1.584]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Flags_Proprs2_0.geometry} material={materials.Proprs2} position={[-3.036, 2.48, 1.33]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cables_cable_0.geometry} material={materials.cable} position={[-5.835, 8.44, 4.464]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.PumpStation_GasPump_0.geometry} material={materials.GasPump} position={[0.622, 0.132, 0.65]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.PumpStation001_GasPump_0.geometry} material={materials.GasPump} position={[-1.571, 0.132, 0.65]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.AdvertStand_ColaAd_0.geometry} material={materials.ColaAd} position={[-0.356, 0.137, 0.608]} rotation={[-Math.PI / 2, 0, 0]} scale={0.567} />
      <mesh geometry={nodes.CactusDesert010_CactusDesert_0.geometry} material={materials.CactusDesert} position={[-9.473, -0.001, -0.982]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.664} />
      <mesh geometry={nodes.CactusDesert011_CactusDesert_0.geometry} material={materials.CactusDesert} position={[3.785, -0.001, -8.211]} rotation={[-Math.PI / 2, 0, 0]} scale={0.713} />
      <mesh geometry={nodes.CactusDesert013_CactusDesert_0.geometry} material={materials.CactusDesert} position={[4.247, -0.001, -8.041]} rotation={[-Math.PI / 2, 0, -1.495]} scale={0.529} />
      <mesh geometry={nodes.CactusNopal014_CactusNopal_0.geometry} material={materials.CactusNopal} position={[8.505, -0.001, 4.783]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Crate005_Props1_0.geometry} material={materials.Props1} position={[0.009, 0.1, -2.338]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.CardbordBox012_Props1_0.geometry} material={materials.Props1} position={[-7.645, 0.212, -3.348]} rotation={[-2.379, -0.017, -1.567]} />
      <mesh geometry={nodes.CardbordBox013_Props1_0.geometry} material={materials.Props1} position={[-6.57, 0.895, -4.068]} rotation={[0.803, -0.554, -1.573]} />
      <mesh geometry={nodes.CardbordBox014_Props1_0.geometry} material={materials.Props1} position={[-6.728, 0.582, -4.391]} rotation={[1.885, -0.553, -1.137]} />
      <mesh geometry={nodes.CardbordBox015_Props1_0.geometry} material={materials.Props1} position={[-6.894, 0.595, -1.852]} rotation={[-2.238, -0.057, -0.042]} />
      <mesh geometry={nodes.Slate001_Proprs2_0.geometry} material={materials.Proprs2} position={[0.14, 3.593, -5.584]} rotation={[-1.57, 0.211, -1.507]} />
      <mesh geometry={nodes.Slate_Proprs2_0.geometry} material={materials.Proprs2} position={[3.03, 2.966, -4.5]} rotation={[-1.584, 0.231, 1.608]} />
      <mesh geometry={nodes.Peg_Proprs2_0.geometry} material={materials.Proprs2} position={[2.329, 2.423, -1.943]} rotation={[Math.PI / 2, -1.449, -3.142]} />
      <mesh geometry={nodes.PaperS_Proprs2_0.geometry} material={materials.Proprs2} position={[3.885, 0, -1.702]} rotation={[-Math.PI / 2, 0, -0.597]} />
      <mesh geometry={nodes.PaperM_Proprs2_0.geometry} material={materials.Proprs2} position={[-2.707, 0, 1.241]} rotation={[-Math.PI / 2, 0, 0.744]} />
      <mesh geometry={nodes.PaperLarge_Proprs2_0.geometry} material={materials.Proprs2} position={[3.923, 0.01, -2.442]} rotation={[-Math.PI / 2, 0, 1.156]} />
      <mesh geometry={nodes.Flags002_Proprs2_0.geometry} material={materials.Proprs2} position={[-2.504, 2.487, 1.203]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.PaperS001_Proprs2_0.geometry} material={materials.Proprs2} position={[6.67, 0.001, -3.161]} rotation={[-Math.PI / 2, 0, -1.505]} />
      <mesh geometry={nodes.PaperS002_Proprs2_0.geometry} material={materials.Proprs2} position={[-7.558, -0.001, 0.485]} rotation={[-Math.PI / 2, 0, -0.04]} />
      <mesh geometry={nodes.PaperLarge001_Proprs2_0.geometry} material={materials.Proprs2} position={[-6.202, 0, -3.126]} rotation={[-Math.PI / 2, 0, 1.905]} />
      <mesh geometry={nodes.PaperLarge002_Proprs2_0.geometry} material={materials.Proprs2} position={[-5.269, -0.001, 5.542]} rotation={[-Math.PI / 2, 0, 0.298]} />
      <mesh geometry={nodes.PaperM001_Proprs2_0.geometry} material={materials.Proprs2} position={[-5.224, 0, -4.551]} rotation={[-Math.PI / 2, 0, 0.475]} />
      <mesh geometry={nodes.PaperM002_Proprs2_0.geometry} material={materials.Proprs2} position={[-8.219, 0.001, -4.024]} rotation={[-Math.PI / 2, 0, 2.367]} />
      <mesh geometry={nodes.PaperM003_Proprs2_0.geometry} material={materials.Proprs2} position={[-1.957, 0.013, -7.466]} rotation={[-Math.PI / 2, 0, 1.958]} />
      <mesh geometry={nodes.PaperM004_Proprs2_0.geometry} material={materials.Proprs2} position={[1.532, 0.002, -8.43]} rotation={[-Math.PI / 2, 0, 2.032]} />
      <mesh geometry={nodes.Signs011_Signs_0.geometry} material={materials.Signs} position={[-2.383, 1.827, 0.655]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Snake_Snake_0.geometry} material={materials.Snake} position={[5.5, 0.427, -4.381]} rotation={[-Math.PI / 2, 0, 1.421]} scale={0.693} />
      <mesh geometry={nodes.Dome_Dome_0.geometry} material={materials.Dome} position={[0, 2.207, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.16} />
      <mesh geometry={nodes.Pig_Pig_0.geometry} material={materials.material} position={[8.067, -0.001, -3.147]} rotation={[-Math.PI / 2, 0, -1.622]} />
      <mesh geometry={nodes.ElectricPole_ElectricPole_0.geometry} material={materials.ElectricPole} position={[-6.086, -0.006, 5.285]} rotation={[-1.551, 0.022, 1.613]} />
      <mesh geometry={nodes.Chair_Furniture_0.geometry} material={materials.Furniture} position={[6.513, -0.09, -5.839]} rotation={[-Math.PI / 2, 0, -0.464]} />
      <mesh geometry={nodes.Bentch_Furniture_0.geometry} material={materials.Furniture} position={[5.341, -0.001, -4.501]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Chair001_Furniture_0.geometry} material={materials.Furniture} position={[7.746, -0.001, -4.191]} rotation={[-Math.PI / 2, 0, -0.907]} />
      <mesh geometry={nodes.Ground_Land_0.geometry} material={materials.Land} position={[-0.055, 4.137, 0.636]} rotation={[-Math.PI / 2, 0, 0]} scale={10.813} />
      <mesh geometry={nodes.Barrel_Proprs2_0.geometry} material={materials.Proprs2} position={[-4.638, 0.565, -5.119]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Barrel001_Proprs2_0.geometry} material={materials.Proprs2} position={[-4.638, 0.565, -6.089]} rotation={[-Math.PI / 2, 0, -1.815]} />
      <mesh geometry={nodes.Barrel002_Proprs2_0.geometry} material={materials.Proprs2} position={[-5.263, 0.554, -5.528]} rotation={[-Math.PI / 2, 0, 0.838]} />
      <mesh geometry={nodes.Barrel003_Proprs2_0.geometry} material={materials.Proprs2} position={[-7.811, -3.094, 2.109]} rotation={[-0.716, -0.351, 0.554]} />
      <mesh geometry={nodes.Barrel004_Proprs2_0.geometry} material={materials.Proprs2} position={[3.857, -4.35, -4.606]} rotation={[-0.39, 0.844, 0.132]} />
      <mesh geometry={nodes.Barrel005_Proprs2_0.geometry} material={materials.Proprs2} position={[2.532, -5.186, -3.987]} rotation={[-2.422, 0.554, 0.547]} />
      <mesh geometry={nodes.tyre_Props1_0.geometry} material={materials.Props1} position={[-4.591, 0.16, -3.233]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.tyre001_Props1_0.geometry} material={materials.Props1} position={[-7.548, 0.027, -0.974]} rotation={[2.782, 0.69, -0.205]} />
      <mesh geometry={nodes.tyre002_Props1_0.geometry} material={materials.Props1} position={[-4.409, 0.16, -4.157]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.tyre003_Props1_0.geometry} material={materials.Props1} position={[-4.421, 0.516, -3.787]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.tyre004_Props1_0.geometry} material={materials.Props1} position={[2.03, 0.135, -8.297]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.tyre005_Props1_0.geometry} material={materials.Props1} position={[8.068, -0.017, 3.854]} rotation={[-1.48, 0.091, 0.564]} />
      <mesh geometry={nodes.tyre006_Props1_0.geometry} material={materials.Props1} position={[0.191, -2.809, 8.767]} rotation={[-2.526, -0.267, -0.189]} />
      <mesh geometry={nodes.tyre007_Props1_0.geometry} material={materials.Props1} position={[4.073, -4.951, -3.274]} rotation={[-1.011, -0.595, 1.574]} />
      <mesh geometry={nodes.tyre008_Props1_0.geometry} material={materials.Props1} position={[-7.169, -3.749, 2.019]} rotation={[-1.707, 0.013, 1.213]} />
      <mesh geometry={nodes.tyre009_Props1_0.geometry} material={materials.Props1} position={[-5.276, -2.422, -6.007]} rotation={[2.359, -0.957, 0.088]} />
      <mesh geometry={nodes.Table_Table_0.geometry} material={materials.Table} position={[6.518, 0, -4.425]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Barrel006_Proprs2_0.geometry} material={materials.Proprs2} position={[-6.81, 0.869, -3.439]} rotation={[2.433, -0.093, -1.55]} />
      <mesh geometry={nodes.tyre010_Props1_0.geometry} material={materials.Props1} position={[-7.327, 0.64, -3.198]} rotation={[-2.18, 1.379, -2.744]} />
      <mesh geometry={nodes.tyre011_Props1_0.geometry} material={materials.Props1} position={[-7.358, 0.458, -3.908]} rotation={[2.576, -0.758, 0.223]} />
      <mesh geometry={nodes['66_66_0'].geometry} material={materials.material_42} position={[-2.762, 0, 5.355]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Ropes_Ropes_0.geometry} material={materials.Ropes} position={[1.755, 1.066, 2.246]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Ropes001_Ropes_0.geometry} material={materials.Ropes} position={[1.704, 1.057, 1.929]} rotation={[-Math.PI / 2, 0.707, 0]} />
      <mesh geometry={nodes.Ropes002_Ropes_0.geometry} material={materials.Ropes} position={[-0.214, 0.6, 2.594]} rotation={[1.925, 0.4, 1.37]} />
    </group>
  )
}

useGLTF.preload('/route_66_adventure_-_sketchfab_challenge.glb')
